# Generated by Django 4.0 on 2024-12-11 18:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator()], verbose_name='Email')),
                ('user_phone', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Номер телефона задается в формате: +7 xxx xxx xx xx', regex='^\\+7 \\d{3} \\d{3} \\d{2} \\d{2}$')], verbose_name='Phone')),
                ('order_date', models.DateField(blank=True, null=True, verbose_name='Order Date')),
                ('lead_text', models.TextField(blank=True, null=True, verbose_name='Lead Text')),
            ],
        ),
    ]
